### ISSUE TITLE
This is not very constructive

### ISSUE THREAD

**Issue by tomraithel** [staltz/prevent-global-this#2]
Please, instead of providing a library that intentionally breaks the web, use your reach to make people participate on the discussion. If we can make W3C aware that the majority of JS developers dislikes the `globalThis` they might reconsider it.

**Comment by okwolf** [comment]
It's about as constructive as [the discussion in the actual proposal](https://github.com/tc39/proposal-global/issues/32#issuecomment-442757353) went.
